### ISSUE TITLE
Error Upon Downloading Invoice (PHP8?)

### ISSUE THREAD

**Issue by corsair** [laravel/cashier-stripe#1037]
- Cashier Version: 12.6.0
- Laravel Version: 8.17.2
- PHP Version: 8.0.0
- Database Driver & Version:
MYSQL (RDS/Aurora)

### Description:
When downloading an invoice using the default examples provided by the Laravel documentation, it appears that either Cashier or otherwise ``dompdf/dompdf`` results in a server error (500) when on PHP8.0. When testing the same function locally on 7.4.2, this error does not occur and allows invoices to be downloaded successfully.

### Steps To Reproduce:
1. Download an invoice PDF using the default code provided on the Laravel Documentation:
```php
Route::get('user/invoice/{invoice}', function (Request $request, $invoiceId) {
    return $request->user()->downloadInvoice($invoiceId, [
        'vendor' => 'Your Company',
        'product' => 'Your Product',
    ]);
});
```

If it matters I am also using the default (unedited) receipt.blade.php provided via:
``php artisan vendor:publish --tag="cashier-views" --force``

**Here is a snippet of the error experienced:**
```
[2020-12-06 10:43:48] production.ERROR: round(): Argument #1 ($num) must be of type int|float, string given {"userId":<redacted>,"exception":"[object] (TypeError(code: 0): round(): Argument #1 ($num) must be of type int|float, string given at /vendor/dompdf/dompdf/src/Css/Style.php:3304)
[stacktrace]
#0 /vendor/dompdf/dompdf/src/Css/Style.php(3304): round()
#1 /vendor/dompdf/dompdf/src/Css/Style.php(888): Dompdf\\Css\\Style->set_z_index()
#2 /vendor/dompdf/dompdf/src/Css/Style.php(948): Dompdf\\Css\\Style->__set()
#3 /vendor/dompdf/dompdf/src/Renderer.php(178): Dompdf\\Css\\Style->__get()
#4 /vendor/dompdf/dompdf/src/FrameReflower/Page.php(148): Dompdf\\Renderer->render()
#5 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Page->reflow()
#6 /vendor/dompdf/dompdf/src/Dompdf.php(815): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#7 /vendor/laravel/cashier/src/Invoice.php(419): Dompdf\\Dompdf->render()
#8 /vendor/laravel/cashier/src/Invoice.php(446): Laravel\\Cashier\\Invoice->pdf()
#9 /vendor/laravel/cashier/src/Invoice.php(434): Laravel\\Cashier\\Invoice->downloadAs()
#10 /vendor/laravel/cashier/src/Concerns/ManagesInvoices.php(177): Laravel\\Cashier\\Invoice->download()
#11 /app/Http/Controllers/User/<redacted>Controller.php(229): App\\Models\\User->downloadInvoice()
```

**Comment by corsair** [comment]
False alarm, it appears this is a known issue with ``dompdf/dompdf`` and currently resolved in a pending Pull Request.

https://github.com/dompdf/dompdf/pull/2313

Closing this issue.
